kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ah-node-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.node.name }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-ah-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
