kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ah-resizer-binding
  labels:
    {{- include "ah-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.controller.name }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-ah-resizer-role
  apiGroup: rbac.authorization.k8s.io
