kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ah-node-driver-registrar-role
  labels:
    {{- include "ah-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
