apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.advancedhosting.com
  labels:
    {{- include "ah-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
