{{- if .Values.serviceAccount.node.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.node.name }}
  labels:
    {{- include "ah-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.node.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
