kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ah-block-storage
  labels:
    {{- include "ah-csi-driver.labels" . | nindent 4 }}
provisioner: csi.advancedhosting.com
allowVolumeExpansion: true
