# Default values for ah-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
apiUrl: ""

image:
  repository: advancedhosting/ah-csi-driver
  pullPolicy: IfNotPresent
  tag: "v0.1.0"


serviceAccount:
  controller:
    create: true
    name: csi-ah-controller-sa
    annotations: {}
  node:
    create: true
    name: csi-ah-node-sa
    annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
