name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Publish
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE: advancedhosting/ah-csi-driver
      run: |
        echo "$DOCKER_IMAGE":"$RELEASE_VERSION"
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
        docker build -t "$DOCKER_IMAGE":"$RELEASE_VERSION"  .
        docker push "$DOCKER_IMAGE":"$RELEASE_VERSION"